import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsOptional, IsString } from 'class-validator';

export class VoiceCommandDto {
  @ApiPropertyOptional({
    description: 'Direct transcribed text or user typed prompt in Hindi or English',
    example: 'Show my latest diabetes lab reports',
  })
  @IsOptional()
  @IsString()
  textCommand?: string;

  @ApiPropertyOptional({
    description: 'Language code for Gnani STT/TTS and AI reasoning',
    example: 'hi-IN',
    default: 'hi-IN',
  })
  @IsOptional()
  @IsString()
  languageCode?: string;

  @ApiPropertyOptional({
    description: 'Base64 encoded audio string if client sends audio payload directly',
  })
  @IsOptional()
  @IsString()
  audioBase64?: string;

  @ApiPropertyOptional({
    description: 'Preferred Gnani voice persona for Text-To-Speech (e.g., Aditi, Karan)',
    example: 'Aditi',
  })
  @IsOptional()
  @IsString()
  voiceName?: string;
}

export class VoiceResponseDto {
  @ApiProperty({ description: 'The speech-to-text transcribed text or echoed text' })
  transcript: string;

  @ApiProperty({ description: 'AI generated text response in the same language as input' })
  responseText: string;

  @ApiPropertyOptional({ description: 'Base64 audio string generated by Gnani TTS or null if fallback' })
  audioBase64?: string | null;

  @ApiProperty({
    description: 'Action payload instructing the frontend what UI action to take',
    example: {
      type: 'SEARCH_RESULTS',
      navigationUrl: '/search?q=diabetes',
      payload: [],
    },
  })
  action: {
    type: 'SEARCH_RESULTS' | 'NAVIGATE_UPLOAD' | 'HEALTH_QA' | 'NAVIGATE';
    navigationUrl?: string;
    payload?: Record<string, unknown> | unknown[] | null;
  };
}
