import { Test, TestingModule } from '@nestjs/testing';
import { ContextSynchronizer, ContextSyncEventType } from './context-synchronizer.service';
import { MemoryLogger } from '../memory/memory-logger.service';

describe('ContextSynchronizer', () => {
  let synchronizer: ContextSynchronizer;
  let queueMock: Record<string, jest.Mock>;
  let loggerMock: Record<string, jest.Mock>;

  beforeEach(async () => {
    queueMock = {
      add: jest.fn().mockResolvedValue({ id: 'job-1' }),
    };

    loggerMock = {
      debug: jest.fn(),
      error: jest.fn(),
      log: jest.fn(),
    };

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        ContextSynchronizer,
        {
          provide: 'BullQueue_ai-context', // token generated by @InjectQueue('ai-context')
          useValue: queueMock,
        },
        {
          provide: MemoryLogger,
          useValue: loggerMock,
        },
      ],
    }).compile();

    synchronizer = module.get<ContextSynchronizer>(ContextSynchronizer);
  });

  it('should be defined', () => {
    expect(synchronizer).toBeDefined();
  });

  it('should trigger sync and log on success', async () => {
    synchronizer.triggerSync({
      userId: 'user_123',
      eventType: ContextSyncEventType.FACT_VALIDATED,
      data: { conditions: [{ id: '1', name: 'Diabetes', status: 'ACTIVE', meta: { version: '1', source: 'test', timestamp: '', confidence: 1, hash: '' } }] },
    });

    expect(queueMock.add).toHaveBeenCalledWith(
      'sync-context',
      expect.objectContaining({
        userId: 'user_123',
        eventType: ContextSyncEventType.FACT_VALIDATED,
      }),
      expect.any(Object),
    );
  });

  it('should expose helper for onFactValidated', () => {
    synchronizer.onFactValidated('user_123', { conditions: [] });
    expect(queueMock.add).toHaveBeenCalledWith(
      'sync-context',
      expect.objectContaining({ eventType: ContextSyncEventType.FACT_VALIDATED }),
      expect.any(Object),
    );
  });

  it('should expose helper for onMedicalRecordConfirmed', () => {
    synchronizer.onMedicalRecordConfirmed('user_123', { labs: [] });
    expect(queueMock.add).toHaveBeenCalledWith(
      'sync-context',
      expect.objectContaining({ eventType: ContextSyncEventType.MEDICAL_RECORD_CONFIRMED }),
      expect.any(Object),
    );
  });
});
